[package]
name = "tic_tac_toe"
version = "0.1.0"
authors = ["Caio Rulli <caiorulli@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
tui = "0.9"
termion = "1.5"
